import React, { useEffect, useMemo, useState } from 'react';
import ReactDOM from 'react-dom/client';
import { ArrowLeft, Bookmark, Check, ChevronRight, Film, Home as HomeIcon, Menu, Play, Search, Sparkles, Star, Tv, X } from 'lucide-react';

const images = {
  dune: 'https://image.tmdb.org/t/p/w780/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
  inception: 'https://image.tmdb.org/t/p/w780/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
  interstellar: 'https://image.tmdb.org/t/p/w780/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
  dark: 'https://image.tmdb.org/t/p/w780/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg',
  oppenheimer: 'https://image.tmdb.org/t/p/w780/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
  arrival: 'https://image.tmdb.org/t/p/w780/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg',
  spider: 'https://image.tmdb.org/t/p/w780/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
  severance: 'https://image.tmdb.org/t/p/w780/pPHpeI2X1qEd1CS1SeyrdhZ4qnT.jpg',
  bear: 'https://image.tmdb.org/t/p/w780/eKfVzzEazSIjJMrw9ADa2x8ksLz.jpg',
  last: 'https://image.tmdb.org/t/p/w780/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg',
};
const catalog = [
  { id:'dune', title:'Dune: Part Two', type:'Movie', year:2024, rating:8.7, runtime:'2h 46m', genre:'Sci-Fi', genres:['Sci-Fi','Adventure','Drama'], image:images.dune, description:'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.', accent:'#d79b62' },
  { id:'inception', title:'Inception', type:'Movie', year:2010, rating:8.8, runtime:'2h 28m', genre:'Thriller', genres:['Thriller','Sci-Fi'], image:images.inception, description:'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.', accent:'#7797a7' },
  { id:'interstellar', title:'Interstellar', type:'Movie', year:2014, rating:8.7, runtime:'2h 49m', genre:'Sci-Fi', genres:['Sci-Fi','Drama'], image:images.interstellar, description:'Explorers travel through a wormhole in space in an attempt to ensure humanityâ€™s survival.', accent:'#bf9b78' },
  { id:'dark', title:'The Dark Knight', type:'Movie', year:2008, rating:9.0, runtime:'2h 32m', genre:'Action', genres:['Action','Crime','Drama'], image:images.dark, description:'Batman faces a criminal mastermind whose reign of chaos pushes Gotham and its heroes to their limits.', accent:'#798797' },
  { id:'oppenheimer', title:'Oppenheimer', type:'Movie', year:2023, rating:8.6, runtime:'3h', genre:'Drama', genres:['Drama','History'], image:images.oppenheimer, description:'The story of J. Robert Oppenheimer and the creation of the atomic bomb.', accent:'#bb805c' },
  { id:'arrival', title:'Arrival', type:'Movie', year:2016, rating:7.9, runtime:'1h 56m', genre:'Sci-Fi', genres:['Sci-Fi','Drama','Mystery'], image:images.arrival, description:'A linguist works with the military to communicate with alien lifeforms after mysterious spacecraft appear around the world.', accent:'#8294a2' },
  { id:'spider', title:'Spider-Man: Across the Spider-Verse', type:'Movie', year:2023, rating:8.6, runtime:'2h 20m', genre:'Animation', genres:['Animation','Action','Adventure'], image:images.spider, description:'Miles Morales catapults across the Multiverse and encounters a team charged with protecting its very existence.', accent:'#d25e55' },
  { id:'severance', title:'Severance', type:'TV Show', year:2022, rating:8.7, runtime:'2 seasons', genre:'Mystery', genres:['Mystery','Drama','Sci-Fi'], image:images.severance, description:'Employees of a mysterious company undergo a procedure that separates their work memories from their personal memories.', accent:'#7698a0' },
  { id:'bear', title:'The Bear', type:'TV Show', year:2022, rating:8.5, runtime:'3 seasons', genre:'Drama', genres:['Drama','Comedy'], image:images.bear, description:'A young chef returns to Chicago to run his familyâ€™s sandwich shop after a devastating loss.', accent:'#c4845a' },
  { id:'last', title:'The Last of Us', type:'TV Show', year:2023, rating:8.7, runtime:'2 seasons', genre:'Drama', genres:['Drama','Adventure'], image:images.last, description:'Twenty years after civilization has been destroyed, a hardened survivor escorts a teenager across a ravaged America.', accent:'#7d9a73' },
];
const genres = ['All','Action','Drama','Sci-Fi','Thriller','Fantasy','Animation','Mystery','Adventure'];
const go = (path) => { window.location.hash = path; window.scrollTo({top:0, behavior:'smooth'}); };
const trailerSearch = (item) => `https://www.youtube.com/results?search_query=${encodeURIComponent(`${item.title} official trailer`)}`;
function useRoute() { const [route,setRoute] = useState(location.hash.slice(1)||'home'); useEffect(()=>{ const f=()=>setRoute(location.hash.slice(1)||'home'); addEventListener('hashchange',f); return()=>removeEventListener('hashchange',f); },[]); return route; }
function Rating({value}) { return <span className="rating"><Star size={14} fill="currentColor" /> {value}</span>; }
function Poster({item, className=''}) { const [bad,setBad]=useState(false); return bad || !item.image ? <div className={`poster-fallback ${className}`} style={{'--accent':item.accent}}><Film size={30}/><span>{item.title}</span></div> : <img className={`poster ${className}`} src={item.image} alt={`${item.title} poster`} loading="lazy" onError={()=>setBad(true)}/>; }
function WatchlistButton({item,saved,onToggle,compact=false}) { return <button className={`watch-button ${compact?'compact':''} ${saved?'saved':''}`} onClick={e=>{e.stopPropagation();onToggle(item.id)}} aria-label={saved?`Remove ${item.title} from watchlist`:`Add ${item.title} to watchlist`}>{saved?<Check size={compact?16:18}/>:<Bookmark size={compact?16:18}/>} {!compact&&(saved?'Saved':'Watchlist')}</button>; }
function Card({item,saved,onToggle}) { return <article className="movie-card" tabIndex="0" onClick={()=>go(`detail/${item.id}`)} onKeyDown={e=>e.key==='Enter'&&go(`detail/${item.id}`)}><div className="poster-wrap"><Poster item={item}/><div className="card-overlay"><button className="round-action" onClick={e=>{e.stopPropagation();go(`detail/${item.id}`)}} aria-label={`View ${item.title}`}><Play size={15} fill="currentColor"/></button><WatchlistButton item={item} saved={saved} onToggle={onToggle} compact/></div></div><div className="card-copy"><div className="card-meta"><span>{item.year}</span><i/> <span>{item.type}</span></div><h3>{item.title}</h3><Rating value={item.rating}/></div></article>; }
function SectionHeader({eyebrow,title,action}) { return <div className="section-header"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{action&&<button className="text-button" onClick={action}>View all <ChevronRight size={16}/></button>}</div>; }
function Nav({route,count}) { const [open,setOpen]=useState(false); const links=[['home','Home',HomeIcon],['movies','Movies',Film],['tv','TV Shows',Tv],['trending','Trending',Sparkles],['watchlist','Watchlist',Bookmark]]; return <header className="navbar"><a className="brand" href="#home"><b><Film size={16}/></b>Cine<span>Synapse</span></a><nav className={open?'nav-links open':'nav-links'}>{links.map(([id,label,Icon])=><a key={id} className={route===id?'active':''} href={`#${id}`} onClick={()=>setOpen(false)}><Icon size={15}/>{label}{id==='watchlist'&&count>0&&<em>{count}</em>}</a>)}</nav><div className="nav-actions"><button className="icon-button" onClick={()=>go('search')} aria-label="Search"><Search size={19}/></button><button className="profile">CS</button><button className="menu-button" onClick={()=>setOpen(!open)} aria-label="Toggle menu">{open?<X/>:<Menu/>}</button></div></header>; }
function Hero({item,saved,onToggle,onNext,spotlightIndex}) { return <section className="hero" style={{'--hero-image':`url(${item.image})`,'--accent':item.accent}}><div className="hero-content"><p className="eyebrow"><Sparkles size={14}/> Spotlight premiere</p><h1 key={item.id} className="hero-title">{item.title}</h1><div className="hero-meta"><Rating value={item.rating}/><span>{item.year}</span><span>{item.runtime}</span><span className="pill">{item.genre}</span></div><p className="hero-description">{item.description}</p><div className="hero-actions"><button className="primary-button" onClick={()=>go(`detail/${item.id}`)}><Play size={16} fill="currentColor"/> View details</button><WatchlistButton item={item} saved={saved} onToggle={onToggle}/></div></div><div className="hero-caption"><span>{String(spotlightIndex+1).padStart(2,'0')}</span><i/><span>Editorâ€™s pick</span><button className="hero-next" onClick={onNext} aria-label="Show next spotlight"><ChevronRight size={17}/></button></div></section>; }
function Home({saved,onToggle}) { const [spotlightIndex,setSpotlightIndex]=useState(0); const spotlight=catalog.slice(0,4); const item=spotlight[spotlightIndex]; const movies=catalog.filter(x=>x.type==='Movie'), shows=catalog.filter(x=>x.type==='TV Show'); const nextSpotlight=()=>setSpotlightIndex(index=>(index+1)%spotlight.length); useEffect(()=>{ const timer=setInterval(nextSpotlight,7000); return()=>clearInterval(timer); },[]); const trending=[...catalog.slice(spotlightIndex),...catalog.slice(0,spotlightIndex)].slice(0,6); return <><Hero item={item} saved={saved.includes(item.id)} onToggle={onToggle} onNext={nextSpotlight} spotlightIndex={spotlightIndex}/><main className="main-content"><section><SectionHeader eyebrow="Curated for you" title="Trending now" action={()=>go('trending')}/><div className="movie-grid">{trending.map(x=><Card key={x.id} item={x} saved={saved.includes(x.id)} onToggle={onToggle}/>)}</div></section><section><SectionHeader eyebrow="Big screen energy" title="Popular movies" action={()=>go('movies')}/><div className="movie-grid">{movies.slice(1,5).map(x=><Card key={x.id} item={x} saved={saved.includes(x.id)} onToggle={onToggle}/>)}</div></section><section><SectionHeader eyebrow="Worth the binge" title="TV shows to obsess over" action={()=>go('tv')}/><div className="movie-grid">{shows.map(x=><Card key={x.id} item={x} saved={saved.includes(x.id)} onToggle={onToggle}/>)}</div></section><GenreStrip/></main></>; }
function GenreStrip() { return <section className="genre-strip"><div><p className="eyebrow">Find your next world</p><h2>Browse by mood.</h2></div><div className="genre-list">{genres.slice(1,7).map((g,i)=><button key={g} onClick={()=>go(`search?genre=${g}`)} style={{'--genre-accent':['#d79b62','#8fa7bd','#c89496','#a4b68e','#a895c0','#d5b174'][i]}}>{g}<ChevronRight size={15}/></button>)}</div></section>; }
function Listing({kind,saved,onToggle}) { const tv=kind==='tv',items=catalog.filter(x=>tv?x.type==='TV Show':x.type==='Movie'); return <main className="main-content listing-page"><div className="page-heading"><div><p className="eyebrow">The collection</p><h1>{tv?'TV shows':'Movies'}</h1><p>Stories with a point of view, ready for your next watch.</p></div><button className="filter-button" onClick={()=>go('search')}><Search size={16}/> Search library</button></div><div className="filter-row"><span>Sort by</span><button className="filter-chip active">Popular</button><button className="filter-chip">Top rated</button><button className="filter-chip">Newest</button></div><div className="movie-grid library-grid">{items.map(x=><Card key={x.id} item={x} saved={saved.includes(x.id)} onToggle={onToggle}/>)}</div></main>; }
function SearchPage({saved,onToggle}) { const [query,setQuery]=useState(''),[genre,setGenre]=useState('All'); const results=useMemo(()=>catalog.filter(x=>`${x.title} ${x.genre} ${x.type}`.toLowerCase().includes(query.toLowerCase())&&(genre==='All'||x.genres.includes(genre))),[query,genre]); return <main className="main-content listing-page"><div className="page-heading"><div><p className="eyebrow">The library</p><h1>Search and discover</h1><p>Find a film, follow a feeling, or browse something new.</p></div></div><label className="search-input"><Search size={20}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search movies, shows, genres..."/>{query&&<button onClick={()=>setQuery('')} aria-label="Clear search"><X size={17}/></button>}</label><div className="genre-filters">{genres.map(g=><button className={genre===g?'active':''} key={g} onClick={()=>setGenre(g)}>{g}</button>)}</div>{results.length?<div className="movie-grid library-grid">{results.map(x=><Card key={x.id} item={x} saved={saved.includes(x.id)} onToggle={onToggle}/>)}</div>:<Empty title="No titles found" text="Try a different title, genre, or search term."/>}</main>; }
function Empty({title,text}) { return <div className="empty-state"><Film size={32}/><h2>{title}</h2><p>{text}</p><button className="primary-button" onClick={()=>go('home')}>Back to home</button></div>; }
function Detail({id,saved,onToggle}) { const item=catalog.find(x=>x.id===id)||catalog[0],related=catalog.filter(x=>x.id!==item.id&&x.genres.some(g=>item.genres.includes(g))).slice(0,4); return <main className="detail-page"><div className="detail-backdrop" style={{'--detail-image':`url(${item.image})`,'--accent':item.accent}}/><div className="detail-top"><button className="back-button" onClick={()=>go('home')}><ArrowLeft size={17}/> Back to browse</button><span>CineSynapse / {item.type}</span></div><div className="detail-hero"><Poster item={item} className="detail-poster"/><div className="detail-copy"><p className="eyebrow">Now playing in your imagination</p><h1>{item.title}</h1><div className="hero-meta"><Rating value={item.rating}/><span>{item.year}</span><span>{item.runtime}</span></div><p>{item.description}</p><div className="detail-actions"><WatchlistButton item={item} saved={saved.includes(item.id)} onToggle={onToggle}/><a className="secondary-button" href={trailerSearch(item)} target="_blank" rel="noopener noreferrer"><Play size={16} fill="currentColor"/> Watch trailer</a></div><div className="detail-tags">{item.genres.map(g=><span key={g}>{g}</span>)}</div></div></div><section className="detail-lower"><p className="eyebrow">Keep exploring</p><h2>You may also like</h2><div className="movie-grid">{related.map(x=><Card key={x.id} item={x} saved={saved.includes(x.id)} onToggle={onToggle}/>)}</div></section></main>; }
function App() { const route=useRoute(), [saved,setSaved]=useState(()=>JSON.parse(localStorage.getItem('cinesynapse-watchlist')||'[]')); useEffect(()=>localStorage.setItem('cinesynapse-watchlist',JSON.stringify(saved)),[saved]); const toggle=id=>setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]); const page=route.split('?')[0]; let content=page==='home'?<Home saved={saved} onToggle={toggle}/>:page==='movies'?<Listing kind="movies" saved={saved} onToggle={toggle}/>:page==='tv'?<Listing kind="tv" saved={saved} onToggle={toggle}/>:page==='search'?<SearchPage saved={saved} onToggle={toggle}/>:page==='trending'?<Listing kind="movies" saved={saved} onToggle={toggle}/>:page==='watchlist'?<main className="main-content listing-page"><div className="page-heading"><div><p className="eyebrow">Your private shelf</p><h1>Watchlist</h1><p>Keep the stories you want close.</p></div></div>{catalog.filter(x=>saved.includes(x.id)).length?<div className="movie-grid library-grid">{catalog.filter(x=>saved.includes(x.id)).map(x=><Card key={x.id} item={x} saved onToggle={toggle}/>)}</div>:<Empty title="Your shelf is waiting" text="Save a title and it will appear here for your next movie night."/>}</main>:page.startsWith('detail/')?<Detail id={page.split('/')[1]} saved={saved} onToggle={toggle}/>:<Home saved={saved} onToggle={toggle}/>; return <div className="app-shell"><Nav route={page} count={saved.length}/>{content}<footer className="footer"><div className="brand"><b><Film size={15}/></b>Cine<span>Synapse</span></div><p>Curated cinema for curious minds.</p><span>Â© 2026 CineSynapse Studio</span></footer></div>; }
ReactDOM.createRoot(document.getElementById('root')).render(<App/>);
